SELECT DATETIME(TIMESTAMP_MILLIS(CAST (Ts AS INT64)), 'Europe/Berlin') AS Ts,
    userID, CAST(bytesSent AS NUMERIC) AS bytesSent, CAST(bytesReceived AS NUMERIC) AS bytesReceived, CAST(bytesReceivedProxy AS NUMERIC) AS bytesReceivedProxy, hostFull, 
    split(hostFull, '.')[ORDINAL(1)] AS host1, 
    split(hostFull, '.')[ORDINAL(2)] AS host2, 
    isHTTPS, 
    CASE WHEN CL_RTT > 0 THEN  CL_RTT END AS CL_RTT, 
    CASE WHEN OS_RTT > 0 THEN  OS_RTT END AS OS_RTT, 
    CASE WHEN CL_Retrans >= 0 THEN  CL_Retrans END AS CL_Retrans, 
    CASE WHEN OS_Retrans >= 0 THEN  OS_Retrans END AS OS_Retrans, 
    CASE WHEN OS_Transmit_time_noSubstract > 0 THEN  OS_Transmit_time_noSubstract END AS OS_Transmit_time_noSubstract, 
    CASE WHEN CL_Transmit_time_noSubstract > 0 THEN  CL_Transmit_time_noSubstract END AS CL_Transmit_time_noSubstract, 
    CASE WHEN OS_Transmit_time > 0 THEN  OS_Transmit_time END AS OS_Transmit_time, 
    CASE WHEN CL_Transmit_time > 0 THEN  CL_Transmit_time END AS CL_Transmit_time, 
    CASE WHEN CL_Transmit_time_noSubstract - CL_Transmit_time >= 0 THEN CL_Transmit_time_noSubstract - CL_Transmit_time END AS CL_inactive_time,
    CASE WHEN OS_Transmit_time_noSubstract - OS_Transmit_time >= 0 THEN OS_Transmit_time_noSubstract - OS_Transmit_time END AS OS_inactive_time,
    CASE WHEN CL_Transmit_time > 0 THEN  CAST(bytesReceived / 1024 / CL_Transmit_time * 1000 AS NUMERIC) END AS download_speed_CL_clean,
    CASE WHEN CL_Transmit_time_noSubstract > 0 THEN CAST(bytesReceived / 1024 / CL_Transmit_time_noSubstract * 1000 AS NUMERIC) END AS download_speed_CL_raw,
    CASE WHEN CL_Transmit_time > 0 THEN CAST(bytesSent / 1024 / CL_Transmit_time * 1000 AS NUMERIC) END AS upload_speed_CL_clean,
    CASE WHEN CL_Transmit_time_noSubstract > 0 THEN CAST(bytesSent / 1024 / CL_Transmit_time_noSubstract * 1000 AS NUMERIC) END AS upload_speed_CL_raw,
    CASE WHEN OS_Transmit_time > 0 THEN CAST(bytesReceivedProxy/ 1024 / OS_Transmit_time * 1000 AS NUMERIC) END AS download_speed_OS_clean,
    CASE WHEN OS_Transmit_time_noSubstract > 0 THEN  CAST(bytesReceivedProxy / 1024 / OS_Transmit_time_noSubstract * 1000 AS NUMERIC) END AS download_speed_OS_raw,
    CASE WHEN OS_Transmit_time > 0 THEN CAST(bytesSent / 1024 / OS_Transmit_time * 1000 AS NUMERIC) END AS upload_speed_OS_clean,
    CASE WHEN OS_Transmit_time_noSubstract > 0 THEN CAST(bytesSent / 1024 / OS_Transmit_time_noSubstract * 1000 AS NUMERIC) END AS upload_speed_OS_raw,
    EXTRACT(HOUR FROM TIMESTAMP_MILLIS(CAST (Ts AS INT64)) AT TIME ZONE 'Europe/Berlin') AS hour
  FROM `case-study-2-nec-team.logs.raw`